### ISSUE TITLE
Cannot import bookmarks from backup json file

### ISSUE THREAD

**Issue by john-james-sf** [ideaweb/nellitab-community#12]
Saved a backup of my bookmarks into a json file.  When I restored from that file, the settings were imported, but none of the bookmarks.

**Comment by ideaweb** [comment]
NelliTab does not offer to make a backup of bookmarks or any other browser data/settings. 

NelliTab backups only (own) settings and (uploaded) icons into NelliTab.

To backup bookmarks please use the bookmark manager of the browser.
