### ISSUE TITLE
Bookmarklets are non-interactive

### ISSUE THREAD

**Issue by JarasM** [ideaweb/nellitab-community#5]
Any bookmarklets (with URL starting with javascript:(function(){ etc) added to bookmarks do show up on the Nellitab, however:

1. They show "?" instead of any kind of meaningful icon (which isn't really that problematic)
2. They cannot be opened from the new tab. Clicking on them doesn't work.

Expectation:
The icon is not a must (apart from a bespoke icon specifically for bookmarklets it's understandable there is no icon to generate from the JS), however the bookmarklets should preferably open normally. They work fine from the regular browser's bookmarks list, as expected.

Running Firefox 79.0 (64bit) on Windows 10.

**Comment by ideaweb** [comment]
Thx for reporting, i will check/add it in the next release.

**Comment by ideaweb** [comment]
Fixed in 2020.7 which will be released soon.

**Comment by JarasM** [comment]
Splendid! Thanks

pon., 21 wrz 2020, 15:15 użytkownik Tom <notifications@github.com> napisał:
