### ISSUE TITLE
Arrow keys to select item, and 'Enter' to open

### ISSUE THREAD

**Issue by emvaized** [ideaweb/nellitab-community#6]
Is it possible to implement item selection with 'arrow' keys? For example, when I open a new tab, I press left/right keys, and switch selection between tab icons in Nelli, and open it with Enter key.

**Comment by ideaweb** [comment]
Added to 2020.8 which will be released soon. 

Please note, it works only if the document (new tab page) is focused. Creating a new tab focuses by default the address bar and you have to click inside the document or use the tab key several times to move the focus into the document. Only Vivaldi has an option in settings to focus the document by default.
