### ISSUE TITLE
Option to display icons in the center of screen

### ISSUE THREAD

**Issue by emvaized** [ideaweb/nellitab-community#7]
I would like to see an option in Settings to display icons in center, when 'tabs' view is enabled.

Current implementation:
![image_1](https://user-images.githubusercontent.com/37851576/91638747-4e2f6680-ea1a-11ea-87b9-fc52439c2bf8.png)

Edited image with the desired option enabled:
![image_2](https://user-images.githubusercontent.com/37851576/91638792-93539880-ea1a-11ea-87dd-7e64173cdd2e.png)

**Comment by ideaweb** [comment]
I will add a new option in upcoming release.

**Comment by ideaweb** [comment]
Added new option "Center sections vertically" in 2020.7 which will be release soon. Please note that tabs are still on top of the screen.

**Comment by emvaized** [comment]
@ideaweb 
Thanks a lot! Happy to hear that.
