### ISSUE TITLE
Top sites disappear after browsing folder in bookmarks

### ISSUE THREAD

**Issue by vukas76** [ideaweb/nellitab-community#8]
The top sites section goes empty after browsing a folder in the Bookmarks section.
Steps to reproduce:
- Open new tab
- Enter a bookmark folder
- Go back.
Refreshing the page solves the problem.

**Comment by ideaweb** [comment]
I cannot reproduce this issue, but i made only some quick tests.

Please could you upload a NelliTab backup file of your configuration here or send it to info@nellitab.io?

**Comment by vukas76** [comment]
Did some more testing. If there is only one line of "Top sites" then the issue doesn't happen.
If there are 2 lines of "Top sites" the issue happens every time a new tab is opened.

**Comment by ideaweb** [comment]
Thx for the hint. Its fixed in 2020.10 which will be released later today.
